### ISSUE TITLE
FSBuilder meeting with Sikt

### ISSUE THREAD

**Issue by SigmundGranaas** [aclgen/aclgen#3]
Meeting with Sikt where we will be introduced to FSBuilder. We will be showed how FSBuilder works as well as how it is used. This will give us great insight into what our application needs to focus on.

**Comment by SigmundGranaas** [comment]
Most important usages of FSBuilder:

Examples for FSBuilder:

General notes:
Grouping objects, everything should be able to group.
Networks
Hosts

Cluster interface for combining firewalls

Firewalls are registered with their intended target.

Router -> vlans -> individual rules for things across vlans.

**Comment by podliashanyk** [comment]
Write meeting minute
